// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: router_agent.proto

package routeragentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RouterAgentMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*RouterAgentMessage_Synchronize
	//	*RouterAgentMessage_Ack
	Message       isRouterAgentMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouterAgentMessage) Reset() {
	*x = RouterAgentMessage{}
	mi := &file_router_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouterAgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouterAgentMessage) ProtoMessage() {}

func (x *RouterAgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_router_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouterAgentMessage.ProtoReflect.Descriptor instead.
func (*RouterAgentMessage) Descriptor() ([]byte, []int) {
	return file_router_agent_proto_rawDescGZIP(), []int{0}
}

func (x *RouterAgentMessage) GetMessage() isRouterAgentMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *RouterAgentMessage) GetSynchronize() *Synchronize {
	if x != nil {
		if x, ok := x.Message.(*RouterAgentMessage_Synchronize); ok {
			return x.Synchronize
		}
	}
	return nil
}

func (x *RouterAgentMessage) GetAck() *CommandAck {
	if x != nil {
		if x, ok := x.Message.(*RouterAgentMessage_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

type isRouterAgentMessage_Message interface {
	isRouterAgentMessage_Message()
}

type RouterAgentMessage_Synchronize struct {
	Synchronize *Synchronize `protobuf:"bytes,1,opt,name=synchronize,proto3,oneof"`
}

type RouterAgentMessage_Ack struct {
	Ack *CommandAck `protobuf:"bytes,2,opt,name=ack,proto3,oneof"`
}

func (*RouterAgentMessage_Synchronize) isRouterAgentMessage_Message() {}

func (*RouterAgentMessage_Ack) isRouterAgentMessage_Message() {}

type RouterAgentCommand struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Command:
	//
	//	*RouterAgentCommand_GetClientInfo
	//	*RouterAgentCommand_AllowClientAccess
	//	*RouterAgentCommand_RevokeClientAccess
	//	*RouterAgentCommand_SetAllowedClients
	//	*RouterAgentCommand_ListNetworkClients
	Command       isRouterAgentCommand_Command `protobuf_oneof:"command"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouterAgentCommand) Reset() {
	*x = RouterAgentCommand{}
	mi := &file_router_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouterAgentCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouterAgentCommand) ProtoMessage() {}

func (x *RouterAgentCommand) ProtoReflect() protoreflect.Message {
	mi := &file_router_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouterAgentCommand.ProtoReflect.Descriptor instead.
func (*RouterAgentCommand) Descriptor() ([]byte, []int) {
	return file_router_agent_proto_rawDescGZIP(), []int{1}
}

func (x *RouterAgentCommand) GetCommand() isRouterAgentCommand_Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *RouterAgentCommand) GetGetClientInfo() *GetClientInfo {
	if x != nil {
		if x, ok := x.Command.(*RouterAgentCommand_GetClientInfo); ok {
			return x.GetClientInfo
		}
	}
	return nil
}

func (x *RouterAgentCommand) GetAllowClientAccess() *AllowClientAccess {
	if x != nil {
		if x, ok := x.Command.(*RouterAgentCommand_AllowClientAccess); ok {
			return x.AllowClientAccess
		}
	}
	return nil
}

func (x *RouterAgentCommand) GetRevokeClientAccess() *RevokeClientAccess {
	if x != nil {
		if x, ok := x.Command.(*RouterAgentCommand_RevokeClientAccess); ok {
			return x.RevokeClientAccess
		}
	}
	return nil
}

func (x *RouterAgentCommand) GetSetAllowedClients() *SetAllowedClients {
	if x != nil {
		if x, ok := x.Command.(*RouterAgentCommand_SetAllowedClients); ok {
			return x.SetAllowedClients
		}
	}
	return nil
}

func (x *RouterAgentCommand) GetListNetworkClients() *ListNetworkClients {
	if x != nil {
		if x, ok := x.Command.(*RouterAgentCommand_ListNetworkClients); ok {
			return x.ListNetworkClients
		}
	}
	return nil
}

type isRouterAgentCommand_Command interface {
	isRouterAgentCommand_Command()
}

type RouterAgentCommand_GetClientInfo struct {
	GetClientInfo *GetClientInfo `protobuf:"bytes,1,opt,name=get_client_info,json=getClientInfo,proto3,oneof"`
}

type RouterAgentCommand_AllowClientAccess struct {
	AllowClientAccess *AllowClientAccess `protobuf:"bytes,2,opt,name=allow_client_access,json=allowClientAccess,proto3,oneof"`
}

type RouterAgentCommand_RevokeClientAccess struct {
	RevokeClientAccess *RevokeClientAccess `protobuf:"bytes,3,opt,name=revoke_client_access,json=revokeClientAccess,proto3,oneof"`
}

type RouterAgentCommand_SetAllowedClients struct {
	SetAllowedClients *SetAllowedClients `protobuf:"bytes,4,opt,name=set_allowed_clients,json=setAllowedClients,proto3,oneof"`
}

type RouterAgentCommand_ListNetworkClients struct {
	ListNetworkClients *ListNetworkClients `protobuf:"bytes,5,opt,name=list_network_clients,json=listNetworkClients,proto3,oneof"`
}

func (*RouterAgentCommand_GetClientInfo) isRouterAgentCommand_Command() {}

func (*RouterAgentCommand_AllowClientAccess) isRouterAgentCommand_Command() {}

func (*RouterAgentCommand_RevokeClientAccess) isRouterAgentCommand_Command() {}

func (*RouterAgentCommand_SetAllowedClients) isRouterAgentCommand_Command() {}

func (*RouterAgentCommand_ListNetworkClients) isRouterAgentCommand_Command() {}

type Synchronize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Synchronize) Reset() {
	*x = Synchronize{}
	mi := &file_router_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Synchronize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Synchronize) ProtoMessage() {}

func (x *Synchronize) ProtoReflect() protoreflect.Message {
	mi := &file_router_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Synchronize.ProtoReflect.Descriptor instead.
func (*Synchronize) Descriptor() ([]byte, []int) {
	return file_router_agent_proto_rawDescGZIP(), []int{2}
}

func (x *Synchronize) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type GetClientInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// All router agents must return identical results for the same request.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IpAddress     string `protobuf:"bytes,2,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClientInfo) Reset() {
	*x = GetClientInfo{}
	mi := &file_router_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClientInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClientInfo) ProtoMessage() {}

func (x *GetClientInfo) ProtoReflect() protoreflect.Message {
	mi := &file_router_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClientInfo.ProtoReflect.Descriptor instead.
func (*GetClientInfo) Descriptor() ([]byte, []int) {
	return file_router_agent_proto_rawDescGZIP(), []int{3}
}

func (x *GetClientInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetClientInfo) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

type AllowClientAccess struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MacAddresses  []string               `protobuf:"bytes,2,rep,name=mac_addresses,json=macAddresses,proto3" json:"mac_addresses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllowClientAccess) Reset() {
	*x = AllowClientAccess{}
	mi := &file_router_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllowClientAccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllowClientAccess) ProtoMessage() {}

func (x *AllowClientAccess) ProtoReflect() protoreflect.Message {
	mi := &file_router_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllowClientAccess.ProtoReflect.Descriptor instead.
func (*AllowClientAccess) Descriptor() ([]byte, []int) {
	return file_router_agent_proto_rawDescGZIP(), []int{4}
}

func (x *AllowClientAccess) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AllowClientAccess) GetMacAddresses() []string {
	if x != nil {
		return x.MacAddresses
	}
	return nil
}

type RevokeClientAccess struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MacAddresses  []string               `protobuf:"bytes,2,rep,name=mac_addresses,json=macAddresses,proto3" json:"mac_addresses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeClientAccess) Reset() {
	*x = RevokeClientAccess{}
	mi := &file_router_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeClientAccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeClientAccess) ProtoMessage() {}

func (x *RevokeClientAccess) ProtoReflect() protoreflect.Message {
	mi := &file_router_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeClientAccess.ProtoReflect.Descriptor instead.
func (*RevokeClientAccess) Descriptor() ([]byte, []int) {
	return file_router_agent_proto_rawDescGZIP(), []int{5}
}

func (x *RevokeClientAccess) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RevokeClientAccess) GetMacAddresses() []string {
	if x != nil {
		return x.MacAddresses
	}
	return nil
}

type SetAllowedClients struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MacAddresses  []string               `protobuf:"bytes,2,rep,name=mac_addresses,json=macAddresses,proto3" json:"mac_addresses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAllowedClients) Reset() {
	*x = SetAllowedClients{}
	mi := &file_router_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAllowedClients) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAllowedClients) ProtoMessage() {}

func (x *SetAllowedClients) ProtoReflect() protoreflect.Message {
	mi := &file_router_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAllowedClients.ProtoReflect.Descriptor instead.
func (*SetAllowedClients) Descriptor() ([]byte, []int) {
	return file_router_agent_proto_rawDescGZIP(), []int{6}
}

func (x *SetAllowedClients) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SetAllowedClients) GetMacAddresses() []string {
	if x != nil {
		return x.MacAddresses
	}
	return nil
}

type ListNetworkClients struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNetworkClients) Reset() {
	*x = ListNetworkClients{}
	mi := &file_router_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNetworkClients) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNetworkClients) ProtoMessage() {}

func (x *ListNetworkClients) ProtoReflect() protoreflect.Message {
	mi := &file_router_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNetworkClients.ProtoReflect.Descriptor instead.
func (*ListNetworkClients) Descriptor() ([]byte, []int) {
	return file_router_agent_proto_rawDescGZIP(), []int{7}
}

func (x *ListNetworkClients) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type NetworkClient struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MacAddress    string                 `protobuf:"bytes,1,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	IpAddresses   []string               `protobuf:"bytes,2,rep,name=ip_addresses,json=ipAddresses,proto3" json:"ip_addresses,omitempty"`
	Hostname      *string                `protobuf:"bytes,3,opt,name=hostname,proto3,oneof" json:"hostname,omitempty"`
	Allowed       bool                   `protobuf:"varint,4,opt,name=allowed,proto3" json:"allowed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkClient) Reset() {
	*x = NetworkClient{}
	mi := &file_router_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkClient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkClient) ProtoMessage() {}

func (x *NetworkClient) ProtoReflect() protoreflect.Message {
	mi := &file_router_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkClient.ProtoReflect.Descriptor instead.
func (*NetworkClient) Descriptor() ([]byte, []int) {
	return file_router_agent_proto_rawDescGZIP(), []int{8}
}

func (x *NetworkClient) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

func (x *NetworkClient) GetIpAddresses() []string {
	if x != nil {
		return x.IpAddresses
	}
	return nil
}

func (x *NetworkClient) GetHostname() string {
	if x != nil && x.Hostname != nil {
		return *x.Hostname
	}
	return ""
}

func (x *NetworkClient) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

type CommandAck struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Id      string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Success bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	// Present only when success=false.
	ErrorMessage *string `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3,oneof" json:"error_message,omitempty"`
	// success=true with mac_address and hostname unset indicates client not found
	MacAddress    *string          `protobuf:"bytes,4,opt,name=mac_address,json=macAddress,proto3,oneof" json:"mac_address,omitempty"`
	Hostname      *string          `protobuf:"bytes,5,opt,name=hostname,proto3,oneof" json:"hostname,omitempty"`
	Clients       []*NetworkClient `protobuf:"bytes,6,rep,name=clients,proto3" json:"clients,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandAck) Reset() {
	*x = CommandAck{}
	mi := &file_router_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandAck) ProtoMessage() {}

func (x *CommandAck) ProtoReflect() protoreflect.Message {
	mi := &file_router_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandAck.ProtoReflect.Descriptor instead.
func (*CommandAck) Descriptor() ([]byte, []int) {
	return file_router_agent_proto_rawDescGZIP(), []int{9}
}

func (x *CommandAck) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CommandAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CommandAck) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

func (x *CommandAck) GetMacAddress() string {
	if x != nil && x.MacAddress != nil {
		return *x.MacAddress
	}
	return ""
}

func (x *CommandAck) GetHostname() string {
	if x != nil && x.Hostname != nil {
		return *x.Hostname
	}
	return ""
}

func (x *CommandAck) GetClients() []*NetworkClient {
	if x != nil {
		return x.Clients
	}
	return nil
}

var File_router_agent_proto protoreflect.FileDescriptor

const file_router_agent_proto_rawDesc = "" +
	"\n" +
	"\x12router_agent.proto\x12.cz.grimir.wifimanager.captive.routeragent.grpc\"\xd0\x01\n" +
	"\x12RouterAgentMessage\x12_\n" +
	"\vsynchronize\x18\x01 \x01(\v2;.cz.grimir.wifimanager.captive.routeragent.grpc.SynchronizeH\x00R\vsynchronize\x12N\n" +
	"\x03ack\x18\x02 \x01(\v2:.cz.grimir.wifimanager.captive.routeragent.grpc.CommandAckH\x00R\x03ackB\t\n" +
	"\amessage\"\xe2\x04\n" +
	"\x12RouterAgentCommand\x12g\n" +
	"\x0fget_client_info\x18\x01 \x01(\v2=.cz.grimir.wifimanager.captive.routeragent.grpc.GetClientInfoH\x00R\rgetClientInfo\x12s\n" +
	"\x13allow_client_access\x18\x02 \x01(\v2A.cz.grimir.wifimanager.captive.routeragent.grpc.AllowClientAccessH\x00R\x11allowClientAccess\x12v\n" +
	"\x14revoke_client_access\x18\x03 \x01(\v2B.cz.grimir.wifimanager.captive.routeragent.grpc.RevokeClientAccessH\x00R\x12revokeClientAccess\x12s\n" +
	"\x13set_allowed_clients\x18\x04 \x01(\v2A.cz.grimir.wifimanager.captive.routeragent.grpc.SetAllowedClientsH\x00R\x11setAllowedClients\x12v\n" +
	"\x14list_network_clients\x18\x05 \x01(\v2B.cz.grimir.wifimanager.captive.routeragent.grpc.ListNetworkClientsH\x00R\x12listNetworkClientsB\t\n" +
	"\acommand\"%\n" +
	"\vSynchronize\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\">\n" +
	"\rGetClientInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x02 \x01(\tR\tipAddress\"H\n" +
	"\x11AllowClientAccess\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rmac_addresses\x18\x02 \x03(\tR\fmacAddresses\"I\n" +
	"\x12RevokeClientAccess\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rmac_addresses\x18\x02 \x03(\tR\fmacAddresses\"H\n" +
	"\x11SetAllowedClients\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rmac_addresses\x18\x02 \x03(\tR\fmacAddresses\"$\n" +
	"\x12ListNetworkClients\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x9b\x01\n" +
	"\rNetworkClient\x12\x1f\n" +
	"\vmac_address\x18\x01 \x01(\tR\n" +
	"macAddress\x12!\n" +
	"\fip_addresses\x18\x02 \x03(\tR\vipAddresses\x12\x1f\n" +
	"\bhostname\x18\x03 \x01(\tH\x00R\bhostname\x88\x01\x01\x12\x18\n" +
	"\aallowed\x18\x04 \x01(\bR\aallowedB\v\n" +
	"\t_hostname\"\xaf\x02\n" +
	"\n" +
	"CommandAck\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12(\n" +
	"\rerror_message\x18\x03 \x01(\tH\x00R\ferrorMessage\x88\x01\x01\x12$\n" +
	"\vmac_address\x18\x04 \x01(\tH\x01R\n" +
	"macAddress\x88\x01\x01\x12\x1f\n" +
	"\bhostname\x18\x05 \x01(\tH\x02R\bhostname\x88\x01\x01\x12W\n" +
	"\aclients\x18\x06 \x03(\v2=.cz.grimir.wifimanager.captive.routeragent.grpc.NetworkClientR\aclientsB\x10\n" +
	"\x0e_error_messageB\x0e\n" +
	"\f_mac_addressB\v\n" +
	"\t_hostname2\xac\x01\n" +
	"\x12RouterAgentService\x12\x95\x01\n" +
	"\aConnect\x12B.cz.grimir.wifimanager.captive.routeragent.grpc.RouterAgentMessage\x1aB.cz.grimir.wifimanager.captive.routeragent.grpc.RouterAgentCommand(\x010\x01B\xe2\x02\n" +
	"2com.cz.grimir.wifimanager.captive.routeragent.grpcB\x10RouterAgentProtoP\x01Z:github.com/wifi-manager/routeragent/internal/routeragentpb\xa2\x02\x06CGWCRG\xaa\x02.Cz.Grimir.Wifimanager.Captive.Routeragent.Grpc\xca\x02.Cz\\Grimir\\Wifimanager\\Captive\\Routeragent\\Grpc\xe2\x02:Cz\\Grimir\\Wifimanager\\Captive\\Routeragent\\Grpc\\GPBMetadata\xea\x023Cz::Grimir::Wifimanager::Captive::Routeragent::Grpcb\x06proto3"

var (
	file_router_agent_proto_rawDescOnce sync.Once
	file_router_agent_proto_rawDescData []byte
)

func file_router_agent_proto_rawDescGZIP() []byte {
	file_router_agent_proto_rawDescOnce.Do(func() {
		file_router_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_router_agent_proto_rawDesc), len(file_router_agent_proto_rawDesc)))
	})
	return file_router_agent_proto_rawDescData
}

var file_router_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_router_agent_proto_goTypes = []any{
	(*RouterAgentMessage)(nil), // 0: cz.grimir.wifimanager.captive.routeragent.grpc.RouterAgentMessage
	(*RouterAgentCommand)(nil), // 1: cz.grimir.wifimanager.captive.routeragent.grpc.RouterAgentCommand
	(*Synchronize)(nil),        // 2: cz.grimir.wifimanager.captive.routeragent.grpc.Synchronize
	(*GetClientInfo)(nil),      // 3: cz.grimir.wifimanager.captive.routeragent.grpc.GetClientInfo
	(*AllowClientAccess)(nil),  // 4: cz.grimir.wifimanager.captive.routeragent.grpc.AllowClientAccess
	(*RevokeClientAccess)(nil), // 5: cz.grimir.wifimanager.captive.routeragent.grpc.RevokeClientAccess
	(*SetAllowedClients)(nil),  // 6: cz.grimir.wifimanager.captive.routeragent.grpc.SetAllowedClients
	(*ListNetworkClients)(nil), // 7: cz.grimir.wifimanager.captive.routeragent.grpc.ListNetworkClients
	(*NetworkClient)(nil),      // 8: cz.grimir.wifimanager.captive.routeragent.grpc.NetworkClient
	(*CommandAck)(nil),         // 9: cz.grimir.wifimanager.captive.routeragent.grpc.CommandAck
}
var file_router_agent_proto_depIdxs = []int32{
	2, // 0: cz.grimir.wifimanager.captive.routeragent.grpc.RouterAgentMessage.synchronize:type_name -> cz.grimir.wifimanager.captive.routeragent.grpc.Synchronize
	9, // 1: cz.grimir.wifimanager.captive.routeragent.grpc.RouterAgentMessage.ack:type_name -> cz.grimir.wifimanager.captive.routeragent.grpc.CommandAck
	3, // 2: cz.grimir.wifimanager.captive.routeragent.grpc.RouterAgentCommand.get_client_info:type_name -> cz.grimir.wifimanager.captive.routeragent.grpc.GetClientInfo
	4, // 3: cz.grimir.wifimanager.captive.routeragent.grpc.RouterAgentCommand.allow_client_access:type_name -> cz.grimir.wifimanager.captive.routeragent.grpc.AllowClientAccess
	5, // 4: cz.grimir.wifimanager.captive.routeragent.grpc.RouterAgentCommand.revoke_client_access:type_name -> cz.grimir.wifimanager.captive.routeragent.grpc.RevokeClientAccess
	6, // 5: cz.grimir.wifimanager.captive.routeragent.grpc.RouterAgentCommand.set_allowed_clients:type_name -> cz.grimir.wifimanager.captive.routeragent.grpc.SetAllowedClients
	7, // 6: cz.grimir.wifimanager.captive.routeragent.grpc.RouterAgentCommand.list_network_clients:type_name -> cz.grimir.wifimanager.captive.routeragent.grpc.ListNetworkClients
	8, // 7: cz.grimir.wifimanager.captive.routeragent.grpc.CommandAck.clients:type_name -> cz.grimir.wifimanager.captive.routeragent.grpc.NetworkClient
	0, // 8: cz.grimir.wifimanager.captive.routeragent.grpc.RouterAgentService.Connect:input_type -> cz.grimir.wifimanager.captive.routeragent.grpc.RouterAgentMessage
	1, // 9: cz.grimir.wifimanager.captive.routeragent.grpc.RouterAgentService.Connect:output_type -> cz.grimir.wifimanager.captive.routeragent.grpc.RouterAgentCommand
	9, // [9:10] is the sub-list for method output_type
	8, // [8:9] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_router_agent_proto_init() }
func file_router_agent_proto_init() {
	if File_router_agent_proto != nil {
		return
	}
	file_router_agent_proto_msgTypes[0].OneofWrappers = []any{
		(*RouterAgentMessage_Synchronize)(nil),
		(*RouterAgentMessage_Ack)(nil),
	}
	file_router_agent_proto_msgTypes[1].OneofWrappers = []any{
		(*RouterAgentCommand_GetClientInfo)(nil),
		(*RouterAgentCommand_AllowClientAccess)(nil),
		(*RouterAgentCommand_RevokeClientAccess)(nil),
		(*RouterAgentCommand_SetAllowedClients)(nil),
		(*RouterAgentCommand_ListNetworkClients)(nil),
	}
	file_router_agent_proto_msgTypes[8].OneofWrappers = []any{}
	file_router_agent_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_router_agent_proto_rawDesc), len(file_router_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_router_agent_proto_goTypes,
		DependencyIndexes: file_router_agent_proto_depIdxs,
		MessageInfos:      file_router_agent_proto_msgTypes,
	}.Build()
	File_router_agent_proto = out.File
	file_router_agent_proto_goTypes = nil
	file_router_agent_proto_depIdxs = nil
}
