// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: router_agent.proto

package routeragentpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RouterAgentService_Connect_FullMethodName = "/cz.grimir.wifimanager.captive.routeragent.grpc.RouterAgentService/Connect"
)

// RouterAgentServiceClient is the client API for RouterAgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RouterAgentServiceClient interface {
	// Single bidirectional stream for agent notifications and server commands.
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RouterAgentMessage, RouterAgentCommand], error)
}

type routerAgentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRouterAgentServiceClient(cc grpc.ClientConnInterface) RouterAgentServiceClient {
	return &routerAgentServiceClient{cc}
}

func (c *routerAgentServiceClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RouterAgentMessage, RouterAgentCommand], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RouterAgentService_ServiceDesc.Streams[0], RouterAgentService_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RouterAgentMessage, RouterAgentCommand]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RouterAgentService_ConnectClient = grpc.BidiStreamingClient[RouterAgentMessage, RouterAgentCommand]

// RouterAgentServiceServer is the server API for RouterAgentService service.
// All implementations must embed UnimplementedRouterAgentServiceServer
// for forward compatibility.
type RouterAgentServiceServer interface {
	// Single bidirectional stream for agent notifications and server commands.
	Connect(grpc.BidiStreamingServer[RouterAgentMessage, RouterAgentCommand]) error
	mustEmbedUnimplementedRouterAgentServiceServer()
}

// UnimplementedRouterAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRouterAgentServiceServer struct{}

func (UnimplementedRouterAgentServiceServer) Connect(grpc.BidiStreamingServer[RouterAgentMessage, RouterAgentCommand]) error {
	return status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedRouterAgentServiceServer) mustEmbedUnimplementedRouterAgentServiceServer() {}
func (UnimplementedRouterAgentServiceServer) testEmbeddedByValue()                            {}

// UnsafeRouterAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RouterAgentServiceServer will
// result in compilation errors.
type UnsafeRouterAgentServiceServer interface {
	mustEmbedUnimplementedRouterAgentServiceServer()
}

func RegisterRouterAgentServiceServer(s grpc.ServiceRegistrar, srv RouterAgentServiceServer) {
	// If the following call panics, it indicates UnimplementedRouterAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RouterAgentService_ServiceDesc, srv)
}

func _RouterAgentService_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RouterAgentServiceServer).Connect(&grpc.GenericServerStream[RouterAgentMessage, RouterAgentCommand]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RouterAgentService_ConnectServer = grpc.BidiStreamingServer[RouterAgentMessage, RouterAgentCommand]

// RouterAgentService_ServiceDesc is the grpc.ServiceDesc for RouterAgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RouterAgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cz.grimir.wifimanager.captive.routeragent.grpc.RouterAgentService",
	HandlerType: (*RouterAgentServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _RouterAgentService_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "router_agent.proto",
}
