spring:
  messages:
    basename: admin-messages,captive-messages
  flyway:
    enabled: false

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  docker:
    compose:
      file: file:${PROJECT_ROOT:.}/app/compose.yml

server:
  forward-headers-strategy: framework

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %5p [%thread] %logger{36}%replace(%X{principal}){'^(.+)$',' principal=$1'}%replace(%X{clientMac}){'^(.+)$',' clientMac=$1'} - %msg%n%wEx"

app:
  locale:
    default: en

wifimanager:
  google:
    directory:
      directory-customer: ${GOOGLE_DIRECTORY_CUSTOMER:my_customer}
      service-account-json-path: ${GOOGLE_LDAP_SERVICE_ACCOUNT_JSON:}
      impersonated-user: ${GOOGLE_LDAP_IMPERSONATED_USER:}
      directory-api-base-url: ${GOOGLE_DIRECTORY_API_BASE_URL:https://admin.googleapis.com/admin/directory/v1}
  captive:
    request-routing:
      ipv4-subnets: ${CAPTIVE_PORTAL_IPV4_SUBNET:[]}
      ipv6-subnets: ${CAPITVE_PORTAL_IPV6_SUBNET:[]}
    portal:
      public-base-url: ${CAPTIVE_PORTAL_PUBLIC_BASE_URL:https://localhost}
    fingerprinting:
      enabled: true
      enforce-threshold: ${CAPTIVE_FINGERPRINTING_ENFORCE_THRESHOLD:70}
      log-threshold: ${CAPTIVE_FINGERPRINTING_LOG_THRESHOLD:40}
      trusted-proxy-enabled: ${CAPTIVE_FINGERPRINTING_TRUSTED_PROXY_ENABLED:true}
      trusted-tls-header-name: ${CAPTIVE_FINGERPRINTING_TRUSTED_PROXY_HEADER_NAME:X-Device-Tls-Fingerprint}
    auth:
      google:
        enabled: ${GOOGLE_LDAP_CAPTIVE_ENABLED:false}
        ldap-url: ldaps://ldap.google.com:636
        user-search-base: ${GOOGLE_LDAP_USER_SEARCH_BASE:}
        user-search-filter: "mail={0}"
        allowed-devices-by-group: ${GOOGLE_LDAP_ALLOWED_DEVICES_BY_GROUP:}
        connect-timeout: 5s
        read-timeout: 5s
      keycloak:
        enabled: ${KEYCLOAK_CAPTIVE_ENABLED:false}
        issuer-uri: ${KEYCLOAK_CAPTIVE_ISSUER_URI:}
        client-id: ${KEYCLOAK_CAPTIVE_CLIENT_ID:}
        client-secret: ${KEYCLOAK_CAPTIVE_CLIENT_SECRET:}
        allowed-devices-by-role: ${KEYCLOAK_CAPTIVE_ALLOWED_DEVICES_BY_ROLE:}
